---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 768

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[fake]
    attributes:
